Implement FixAllProvider for RCS1014
JosefPihrt/Roslynator pull request #1070
Opened 2023-04-13 22:40 UTC by jamesHargreaves12

This PR introduces a new FixAllProvider for RCS1014, designed to apply code fixes sequentially in reverse order by location within the document. This approach is safe because applying a given code fix for RCS1014 will not impact the text prior to it.

The FixAllProvider is constructed to minimize its coupling to any RCS1014-specific logic, making it easier to extend for other code fixes that satisfy the following property:
- Applying a code fix for Diagnostic X at location Y would not change the location, validity or code fixes of a Diagnostics of the same type as X but that occurs earlier in the file

As an aside, when first looking at this, I tried using WellKnownFixAllProviders.BatchFixAll rather than implementing something new. On occasion, this was found to produce garbage code. For example:
```
    public static TheoryData<string[], int[]?, int[]?, int[]?, int[]?, int?[]?, int[]> M()
    {
        var l = nameof(X);
        var r = nameof(Y);
        return new()
        {
            { new[] { l, l, r, r }, null, null, new[] { 1 }, null, null, new[] { 1, 3, 0, 2 } },
            { new[] { l, l, l, r, r, r }, null, null, null, null, null, new[] { 2 } },
        };
    }
```
Gets converted to the following:
```
    public static TheoryData<string[], int[]?, int[]?, int[]?, int[]?, int?[]?, int[]> M()
    {
        var l = nameof(X);
        var r = nameof(Y);
        return new()
        {
            { new string[] { l, l, r, r }, null, null, new[] { 1 }, null, null, new[] { 1, 3, 0, 2 } },
            { new int[] { 1 }, null, null, new[] { l, l, l, r, r, r }, null, null, null, null, null, new int[] { 2 } },
        };
    }
```
I did some debugging here and this is an issue within the merge algorithm of WellKnownFixAllProviders.BatchFixAll. After reviewing related discussions on the Roslyn GitHub, it became evident that this FixAllProvider is not expected to work in all scenarios, and implementing a custom solution is preferred.

2023-04-14 10:35 UTC, JosefPihrt commented
Hi,

it would be better to open a new issue first and then open a PR.

I used your code sample (+ I used `TheoryData` from xUnit). I applied code fix "Use explicitly typed array" with option "Fix all occurrences in document". The result is as expected:

```
    public static TheoryData<string[], int[]?, int[]?, int[]?, int[]?, int?[]?, int[]> M()
    {
        var l = nameof(X);
        var r = nameof(Y);
        return new()
        {
            { new string[] { l, l, r, r }, null, null, new int[] { 1 }, null, null, new int[] { 1, 3, 0, 2 } },
            { new string[] { l, l, l, r, r, r }, null, null, null, null, null, new int[] { 2 } },
        };
    }
```

2023-04-20 23:16 UTC, jamesHargreaves12 commented
I am surprised that you didn't run into the same issue. But I have opened an Issue as requested that contains a more full description of how to reproduce the issue. https://github.com/JosefPihrt/Roslynator/issues/1075

2023-07-28 20:44 UTC, JosefPihrt requested changes

2023-07-28 20:44 UTC, JosefPihrt commented on src/Analyzers.CodeFixes/CSharp/CodeFixes/UseExplicitlyOrImplicitlyTypedArrayFixAllProvider.cs
> +        }
What if diagnostic are nested? Will it work then?

2023-08-14 09:37 UTC, JosefPihrt commented on src/Analyzers.CodeFixes/CSharp/CodeFixes/UseExplicitlyOrImplicitlyTypedArrayFixAllProvider.cs
> +        }
👍

2023-08-14 09:43 UTC, JosefPihrt requested changes

2023-08-14 09:43 UTC, JosefPihrt commented on src/Analyzers.CodeFixes/CSharp/CodeFixes/UseExplicitlyOrImplicitlyTypedArrayCodeFixProvider.cs
> +            _ => "",
This arm is unreachable, so I would prefer to throw InvalidOperationException.

2023-08-14 09:43 UTC, JosefPihrt commented on src/Analyzers.CodeFixes/CSharp/CodeFixes/UseExplicitlyOrImplicitlyTypedArrayCodeFixProvider.cs
> +            _ => null
This arm is unreachable, so I would prefer to throw InvalidOperationException.

2023-08-16 21:46 UTC, JosefPihrt commented on ChangeLog.md
> +- Add Custom FixAllProvider for [RCS1014](https://github.com/JosefPihrt/Roslynator/blob/main/docs/analyzers/RCS1014.md) ([#1070](https://github.com/JosefPihrt/Roslynator/pull/1070)).
```suggestion
- Add custom FixAllProvider for [RCS1014](https://github.com/JosefPihrt/Roslynator/blob/main/docs/analyzers/RCS1014.md) ([#1070](https://github.com/JosefPihrt/Roslynator/pull/1070)).
```

2023-08-16 22:39 UTC, JosefPihrt approved these changes

2023-08-16 22:40 UTC, merged