Fix RCS1216
JosefPihrt/Roslynator pull request #1094
Opened 2023-06-05 22:09 UTC by jamesHargreaves12

Currently, if an unsafe local block is located inside a for statement then one of the asserts will fail https://github.com/JosefPihrt/Roslynator/blob/1d035ba7b32fafd9057e3c02f3a903a1493ae212/src/Analyzers/CSharp/Analysis/UnnecessaryUnsafeContextAnalyzer.cs#L248

For example
```
    class C
    {
        unsafe void M()
        {
            for(int y = 0; y < 10; y ++){
                unsafe void M2() {
                    var x = 1;
                }
            }
        }
    }
```
To fix this and make the code easier to grok I refactored the 3 distinct methods of walking up the syntax tree checking for unsafe modifiers into a single loop. I also Added a new test suite for the analyzer/code fix of RCS1216 as one currently does not exist.

2023-06-06 09:14 UTC, JosefPihrt requested changes
If you want to simplify the code even more, the method

```
private static void AnalyzeMemberDeclaration(SyntaxNodeAnalysisContext context)
```
can include all type declarations and member declarations. Virtually all cases except UnsafeStatement and LocalFunctionStatement.

2023-06-06 09:14 UTC, JosefPihrt commented on src/Tests/Analyzers.Tests/RCS1216UnnecessaryUnsafeContextTests.cs
> +".Replace("<member_signature>", memberSignature);
This "replace" pattern is not used anywhere in the unit tests. Please create separate method for each case.

2023-06-06 09:14 UTC, JosefPihrt commented on src/Tests/Analyzers.Tests/RCS1216UnnecessaryUnsafeContextTests.cs
> +
Unnecessary empty lines.

2023-06-09 19:48 UTC, JosefPihrt requested changes

2023-06-10 11:36 UTC, jamesHargreaves12 commented on src/Analyzers/CSharp/Analysis/UnnecessaryUnsafeContextAnalyzer.cs
> +            switch (node)
Ah, good point - I misunderstood what you were asking

2023-06-22 08:35 UTC, JosefPihrt approved these changes

2023-06-22 08:35 UTC, merged